DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Clients'[Client Region],
			'Clients'[Client Status],
			"SumContract_Value", CALCULATE(SUM('Clients'[Contract Value]))
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(501, __DS0Core, 'Clients'[Client Region], 1, 'Clients'[Client Status], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Clients'[Client Region], 'Clients'[Client Status]