table Clients
	lineageTag: 6a46f941-6635-474d-8fbc-7d809114b767

	column 'Client Name'
		dataType: string
		lineageTag: c9386ffd-7121-411e-8a8f-fbddc87806a8
		summarizeBy: none
		sourceColumn: Client Name

		annotation SummarizationSetBy = Automatic

	column 'Client Address'
		dataType: string
		lineageTag: 624077e2-0fe1-4997-b138-63bf00166774
		summarizeBy: none
		sourceColumn: Client Address

		annotation SummarizationSetBy = Automatic

	column 'Client Email'
		dataType: string
		lineageTag: 792cd6c1-aad8-473d-b6af-2a0b535099fc
		summarizeBy: none
		sourceColumn: Client Email

		annotation SummarizationSetBy = Automatic

	column 'Client Region'
		dataType: string
		lineageTag: 50f9d87b-eaaa-4d45-8d79-4b196455f079
		summarizeBy: none
		sourceColumn: Client Region

		annotation SummarizationSetBy = Automatic

	column 'Trade Status'
		dataType: string
		lineageTag: 9caee4d6-d441-442d-995b-2e21c3a71402
		summarizeBy: none
		sourceColumn: Trade Status

		annotation SummarizationSetBy = Automatic

	column 'Trade Value'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9bc77d92-b482-4f37-8b38-b0ad2c51556c
		summarizeBy: sum
		sourceColumn: Trade Value

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 97abe0cc-2ec7-4c76-b670-15f15aae5012
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Clients = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Presentations\2025.11.12 Austin User Group\client_df.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Client Name", type text}, {"Client Address", type text}, {"Client Email", type text}, {"Client Region", type text}, {"Client Status", type text}, {"Contract Value", Currency.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Contract Value", "Trade Value"}, {"Client Status", "Trade Status"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

