table Rejected
	lineageTag: f5f1dcb0-9377-4ff4-8235-c23a19afa9e0

	column 'Client Name'
		dataType: string
		lineageTag: 869de25f-0943-48d5-9765-4ffe4baf206b
		summarizeBy: none
		sourceColumn: Client Name

		annotation SummarizationSetBy = Automatic

	column 'Client Address'
		dataType: string
		lineageTag: da17ab4c-c4c4-4c9d-9e4f-7b5672d23521
		summarizeBy: none
		sourceColumn: Client Address

		annotation SummarizationSetBy = Automatic

	column 'Client Email'
		dataType: string
		lineageTag: 2f6dd95e-20f7-49ab-86e7-a63ba9c952c4
		summarizeBy: none
		sourceColumn: Client Email

		annotation SummarizationSetBy = Automatic

	column 'Client Region'
		dataType: string
		lineageTag: 6e64f806-8495-4ea5-a94d-ec5875a30e74
		summarizeBy: none
		sourceColumn: Client Region

		annotation SummarizationSetBy = Automatic

	column 'Trade Status'
		dataType: string
		lineageTag: 89a4159b-708a-4f19-b2b7-4d837fdf4b0e
		summarizeBy: none
		sourceColumn: Trade Status

		annotation SummarizationSetBy = Automatic

	column 'Trade Value'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a239695f-7763-42cd-a75c-7603f7818d74
		summarizeBy: sum
		sourceColumn: Trade Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: d7db18c7-bbbd-465e-af75-4a28980db5cf
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Rejected = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Presentations\2025.11.12 Austin User Group\client_df.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Client Name", type text}, {"Client Address", type text}, {"Client Email", type text}, {"Client Region", type text}, {"Client Status", type text}, {"Contract Value", Currency.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Contract Value", "Trade Value"}, {"Client Status", "Trade Status"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Trade Status] = "Rejected")),
				    #"Added Index" = Table.AddIndexColumn(#"Filtered Rows", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

