DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"In Progress"}, 'Clients'[Client Status])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Clients'[Client Name],
			'Clients'[Client Status],
			__DS0FilterTable,
			"SumContract_Value", CALCULATE(SUM('Clients'[Contract Value]))
		)


EVALUATE
	__DS0Core

ORDER BY
	[SumContract_Value] DESC, 'Clients'[Client Name], 'Clients'[Client Status]