DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Clients'[Client Region],
			'Clients'[Client Status],
			"SumContract_Value", CALCULATE(SUM('Clients'[Contract Value]))
		)

EVALUATE
	__DS0Core

ORDER BY
	'Clients'[Client Region], 'Clients'[Client Status]