// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"Rejected"}, 'Clients'[Trade Status])

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Rejected'[Index])),
			AND('Rejected'[Index] >= 1, 'Rejected'[Index] <= 20)
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Rejected'[Client Name],
			'Rejected'[Trade Status],
			__DS0FilterTable,
			__DS0FilterTable2,
			"Trade Value", CALCULATE(SUM('Rejected'[Trade Value]))
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(501, __DS0Core, 'Rejected'[Client Name], 1, 'Rejected'[Trade Status], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Rejected'[Client Name], 'Rejected'[Trade Status]
