// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"Rejected"}, 'Clients'[Trade Status])

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Clients'[Index])),
			AND('Clients'[Index] >= 1, 'Clients'[Index] <= 20)
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Clients'[Client Name],
			'Clients'[Trade Status],
			__DS0FilterTable,
			__DS0FilterTable2,
			"Trade Value", CALCULATE(SUM('Clients'[Trade Value]))
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(501, __DS0Core, [Trade Value], 0, 'Clients'[Client Name], 1, 'Clients'[Trade Status], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[Trade Value] DESC, 'Clients'[Client Name], 'Clients'[Trade Status]
